//! Items for code generated by the runtime macros.

pub use serde;

use crate::{deserialize_tagged, serialize_tagged};

/// Serializes the fields of a `#[record]` struct in the browser's format.
///
/// # Errors
///
/// Returns an error if a field fails to serialize.
pub fn serialize_record<T, S>(serializer: S, fields: &T) -> Result<S::Ok, S::Error>
where
    T: serde::Serialize,
    S: serde::Serializer,
{
    serialize_tagged(serializer, "Record", fields)
}

/// Deserializes the fields of a `#[record]` struct from the browser's format.
///
/// # Errors
///
/// Returns an error if the input is not a record or a field is invalid.
pub fn deserialize_record<'de, T, D>(deserializer: D) -> Result<T, D::Error>
where
    T: serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    deserialize_tagged(deserializer, "Record")
}
